version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_human
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: human_backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      -  MONGODB_URL=mongodb://mongo:27017/hms
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: human_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data: